### ISSUE TITLE
Nault 1.10.2-Linux.Appimage does not work on Tails 4.16

### ISSUE THREAD

**Issue by more4521** [Nault/Nault#337]
**Describe the bug**
Hi.  I'm planning to use Nault desktop application in Tails for privacy & security reasons.  I understand that Linux.AppImage should work on any distribution where AppImage are supported, in particular Tails.  I read that other AppImages are working fine in Tails.  However, my experience is that Nault AppImage does not work on Tails. 

**To Reproduce**
1. I have Tails 4.16 working without any known issue, with Persistent drive
2. I have downloaded Nault-1.10.2-Linux.AppImage from github.
3. I have verifed the downloaded AppImage file using the checksums-1.10.2-linux.txt file
4. I have created a folder in /home/amnesia/Persistent/Nault
5. I have copied Nault AppImage file ( and chechsums file)
6. On a terminal I have added execute rights with command "chmod +x Nault-1.10.2-Linux.AppImage"
7. I have executed "./Nault-1.10.2-Linux.AppImage" 

The following error message is shown:
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EAFNOSUPPORT, Address family not supported by protocol
    at new Hci (/tmp/.mount_Nault-4rRNDA/resources/app.asar/node_modules/@abandonware/noble/lib/hci-socket/hci.js:74:18)
    at new NobleBindings (/tmp/.mount_Nault-4rRNDA/resources/app.asar/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:25:15)
    at Object.<anonymous> (/tmp/.mount_Nault-4rRNDA/resources/app.asar/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:546:18)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)

The same AppImage file works fine on an OpenSuse Trumbleweek VM. 

**Description of what you expected to happen.
I expect that the Nault window is displayed as observed on a OpenSuse Trumbleweek VM

**Screenshots**
No Screenshots since application does not start.

**Web (please complete the following information):**
 No Web application

**Smartphone (please complete the following information):**
No Smartphone application

**Desktop App (please complete the following information):**
 - OS: Tails 4.16
 - Version: 1.10.2

**Additional context**
I have obseved the same error with a previous Nault AppImage and a previous Tails version.
Tails Persistant drive is configured with option "DotFiles".  I observed that .nault files are not created.

**Comment by joaofvfonseca** [comment]
The problem seems to be related to what was described in #301.
Maybe take advantage of AppImage/AppImageKit@d17fdefadcb98befa66c29137ce25731256f8f2a and instead of writing to `/tmp`, write to `./Nault-Linux.AppImage.home`?

**Comment by SparK-Cruz** [comment]
Same error
Tails 6.14.2
Nault 1.18.2

**Comment by iMathX-o** [comment]
Even disabling the Bluetooth module and forcing output via IPv4, the problem persists.

Tails 6.14.2
Nault 1.18.2
