### ISSUE TITLE
Update to Nault-1.10.3-Linux.AppImage broke startup

### ISSUE THREAD

**Issue by tjhann** [Nault/Nault#350]
After updating `Nault-1.10.2` to `Nault-1.10.3` on `Ubuntu 18.04.5 LTS`, Nault cannot find `glibc_2.28` and gets jammed at startup.

This version of Ubuntu doesn't seem to have `glibc_2.28` available through the package manager. The solution for me seems to be to update to newer Ubuntu, but Nault should not break like this due to an update, especially an update downloaded by Nault itself.

Here's the error:
```
% ./Nault-1.10.3-Linux.AppImage
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.KJFS38)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/tmp/.mount_Nault-JXl8pm/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/tmp/.mount_Nault-JXl8pm/resources/app.asar/node_modules/usb/usb.js:1:57)
```

**Comment by Joohansson** [comment]
I'm quite sure this is because we use "ubuntu-latest" when building the electron app which is now using Ubuntu 20 by default instead of 18 (a choice made by Github). So the question is if we should roll back and force use 18 or let Nault require Ubuntu 20 as min version. Not sure how else this can be fixed.
https://github.com/actions/virtual-environments/issues/1816

We had to apply this fix: https://github.com/Nault/Nault/pull/340

**Comment by BitDesert** [comment]
We should not revert to Ubuntu 18 as Ubuntu 20 LTS is already one year old.

Maybe you can install gcc on your computer?

**Comment by tjhann** [comment]
Installed new system and it's actually Xubuntu (I just copy pasted what `lsb_release -s -d`gave me). It was time to switch anyway because `Xubuntu 18.04 LTS` support ends in April.

So now it's working.
