### ISSUE TITLE
Nault 1.18.3 Debian sid - crashing at start

### ISSUE THREAD

**Issue by brokechubb** [Nault/Nault#603]
$ ./Nault-1.18.3-Linux.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@ledgerhq/devices/hid-framing'
Require stack:
- /tmp/.mount_Nault-rcCDZL/resources/app.asar/node_modules/@ledgerhq/hw-transport-node-hid-noevents/lib/TransportNodeHid.js
- /tmp/.mount_Nault-rcCDZL/resources/app.asar/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js
- /tmp/.mount_Nault-rcCDZL/resources/app.asar/desktop-app/dist/lib/ledger.js
- /tmp/.mount_Nault-rcCDZL/resources/app.asar/desktop-app/dist/desktop-app.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:681)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/.mount_Nault-rcCDZL/resources/app.asar/node_modules/@ledgerhq/hw-transport-node-hid-noevents/lib/TransportNodeHid.js:62:37)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)

**Comment by Joohansson** [comment]
Please use 1.8.2 until we have fixed this: https://github.com/Nault/Nault/releases/tag/v1.18.2
