### ISSUE TITLE
Error: Cannot find module './desktop-app/src/lib/ledger'

### ISSUE THREAD

**Issue by iljah** [Nault/Nault#72]
Installed from source as described in documentation:
```
...
npm install
npm run wallet:build-desktop
npm run desktop:local
```
on fedora 32 and tried to run but got:
```
$ desktop-app/build/Nault-1.5.2.AppImage   
Starting ledger@!
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './desktop-app/src/lib/ledger'
Require stack:
- /tmp/.mount_Nault-vFwEN9/resources/app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:281:679)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/.mount_Nault-vFwEN9/resources/app.asar/main.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```
and nothing else seems to happen. Is something wrong or should I just wait longer?

**Comment by BitDesert** [comment]
If your build didn't get any errors this seems to be weird...
Is the prebuilt AppImage working for you? https://github.com/BitDesert/Nault/releases/download/v1.6.1/Nault-1.6.1.AppImage

**Comment by iljah** [comment]
How do I convert checksum in yml to hex?

**Comment by BitDesert** [comment]
I'm not familiar how this works in Fedora. You probably have to find that out yourself or ditch the checksum for testing purposes.

**Comment by iljah** [comment]
This isn't related to fedora because release page writes `shasum -a 512 <filename>` which gives: `354ba4e79789a8cd082994239c7eb61620246110c0a3f6a9a4cbe6c2ec4a24bf78420012ef29605d01b4bfbc305fc124f5183d628fd71b00dbcea78e9bc7f398  Nault-1.6.1.AppImage`

Release page also writes "Hashes are available in the latest-*.yml files." but there I see `NUuk55eJqM0IKZQjnH62FiAkYRDAo/appMvmwuxKJL94QgAS7ylgXQG0v7wwX8Ek9Rg9Yo/XGwDbzqeOm8fzmA==` which is clearly different from that given by sha512sum. How do you verify that you've put correct checksum in yml?

**Comment by BitDesert** [comment]
You're right, they seem to be also base64 encoded.

**Comment by iljah** [comment]
I tried base64 but didn't realize its result should be converted to hex: 
```
$ echo NUuk55eJqM0IKZQjnH62FiAkYRDAo/appMvmwuxKJL94QgAS7ylgXQG0v7wwX8Ek9Rg9Yo/XGwDbzqeOm8fzmA==|base64 -d|hexdump -v -e '1/1 "%02x"'
354ba4e79789a8cd082994239c7eb61620246110c0a3f6a9a4cbe6c2ec4a24bf78420012ef29605d01b4bfbc305fc124f5183d628fd71b00dbcea78e9bc7f398
```

**Comment by iljah** [comment]
Prebuilt app image seems to work.

**Comment by iljah** [comment]
Is complaint in OP related to ledger hw wallet or nano public ledger?

**Comment by BitDesert** [comment]
Can you try removing your old AppImage and running `npm run desktop:build` ?

**Comment by iljah** [comment]
Removed old and ran `npm run desktop:build && npm run desktop:local`, same result. Outputs from above:
```
> nault@1.5.2 desktop:build .../Nault
> npm run wallet:build-desktop && npm run desktop:compile


> nault@1.5.2 wallet:build-desktop .../Nault
> ng build --configuration=desktop --base-href 

Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {2} polyfills-es2015.31afa9b1becf4670c3f7.js (polyfills) 157 kB [initial] [rendered]
chunk {3} polyfills-es5.da7539d067d19605b093.js (polyfills-es5) 250 kB [initial] [rendered]
chunk {} df4222b31b0aa9f6d820.worker.js 71.8 kB  [rendered]
chunk {} df4222b31b0aa9f6d820.worker.js 72.5 kB  [rendered]
chunk {1} main-es2015.2eaccdd0e305c575fe78.js (main) 1.53 MB [initial] [rendered]
chunk {1} main-es5.2eaccdd0e305c575fe78.js (main) 1.63 MB [initial] [rendered]
chunk {0} runtime-es2015.0dae8cbc97194c7caed4.js (runtime) 1.45 kB [entry] [rendered]
chunk {0} runtime-es5.0dae8cbc97194c7caed4.js (runtime) 1.45 kB [entry] [rendered]
chunk {4} styles.144dc5ef9bb248389fde.css (styles) 417 bytes [initial] [rendered]
Date: 2020-07-27T18:01:22.763Z - Hash: e3c4ef90f32ccbcf6485 - Time: 23947ms
```

```
  • electron-builder  version=22.7.0 os=5.7.9-200.fc32.x86_64
  • loaded configuration  file=package.json ("build" field)
  • Specified application directory equals to project dir — superfluous or wrong configuration  appDirectory=./
  • writing effective config  file=desktop-app/build/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=node-hid@1.3.0, usb@1.6.3 platform=linux arch=x64
  • install prebuilt binary  name=usb version=1.6.3 platform=linux arch=x64
  • install prebuilt binary  name=node-hid version=1.3.0 platform=linux arch=x64
  • build native dependency from sources  name=usb
                                          version=1.6.3
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.5
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ .../.npm/_prebuilds/b86853-usb-v1.6.3-electron-v80-linux-x64.tar.gz
    prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-electron-v80-linux-x64.tar.gz
    prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-electron-v80-linux-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=9.1.1 runtime=electron arch=x64 libc= platform=linux)
    
  • packaging       platform=linux arch=x64 electron=9.1.1 appOutDir=desktop-app/build/linux-unpacked
  • building        target=AppImage arch=x64 file=desktop-app/build/Nault-1.5.2.AppImage
```

**Comment by iljah** [comment]
desktop:build alone didn't create AppImage

**Comment by Joohansson** [comment]
@iljah npm run desktop:build-local seems to be the full command. It internally calls desktop:build and desktop:local where desktop:build calls wallet:build-desktop and desktop:compile. But sounds like that didn't work for you either.

**Comment by iljah** [comment]
Correct, same result as originally. Actually I didn't update to latest version so hang on...

**Comment by iljah** [comment]
Now it worked, thanks!

**Comment by BitDesert** [comment]
And I think you executed `npm run desktop` which somehow defaults to a wrong electron file `main.js`. Those got deleted now.
